=== transformerlab/transformerlab-api/test/plugins/plugin.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "uniqueId": { "type": "string" },
    "description": { "type": "string" },
    "plugin-format": { "type": "string" },
    "type": {
      "type": "string",
      "enum": [
        "loader",
        "trainer",
        "evaluator",
        "generator",
        "eval",
        "exporter",
        "rag",
        "diffusion"
      ]
    },
    "version": { "type": "string" },
    "model_architectures": {
      "type": "array",
      "items": { "type": "string" }
    },
    "supported_hardware_architectures": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["cuda", "mlx", "cpu", "amd"]
      }
    },
    "files": {
      "type": "array",
      "items": { "type": "string" }
    },
    "setup-script": { "type": "string" },
    "parameters": { "type": "object" },
    "parameters_ui": { "type": "object" }
  },
  "required": [
    "name",
    "uniqueId",
    "description",
    "plugin-format",
    "type",
    "version",
    "files",
    "setup-script",
    "supported_hardware_architectures"
  ],
  "additionalProperties": true
}

=== transformerlab/transformerlab-api/transformerlab/plugins/mlx_vlm_server/index.json
{
  "name": "MLX Vision Server",
  "uniqueId": "mlx_vlm_server",
  "description": "MLX Machine learning multimodal research on your laptop or in a data center - by Blaizzy",
  "plugin-format": "python",
  "type": "loader",
  "version": "0.1.20",
  "model_architectures": ["LlavaForConditionalGeneration"],
  "supported_hardware_architectures": [
    "mlx"
  ],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {}
}

=== transformerlab/transformerlab-api/transformerlab/plugins/ollama_server/index.json
{
  "name": "Ollama Server",
  "uniqueId": "ollama_server",
  "description": "Connects to your instance of ollama to run GGUF models that can host models across GPU and/or CPU.",
  "plugin-format": "python",
  "type": "loader",
  "version": "0.1.3",
  "model_architectures": ["GGUF"],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {},
  "supported_hardware_architectures": ["cpu", "cuda", "mlx"]
}

=== transformerlab/transformerlab-api/transformerlab/plugins/fastchat_vision_server/index.json
{
    "name": "Fastchat Multimodal Server",
    "uniqueId": "fastchat_vision_server",
    "description": "Fastchat loads vision models for inference using Huggingface Transformers for generation.",
    "plugin-format": "python",
    "type": "loader",
    "version": "1.0.5",
    "model_architectures": [
      "LlavaForConditionalGeneration",
      "Mistral3ForConditionalGeneration"
    ],
    "supported_hardware_architectures": [
    "cpu",
    "cuda",
    "mlx"
  ],
    "files": [
      "main.py",
      "setup.sh"
    ],
    "setup-script": "setup.sh",
    "parameters": {
      "num_gpus": {
        "title": "Number of GPUs",
        "type": "integer"
      },
      "eight_bit": {
        "title": "Enable 8-bit compression",
        "type": "boolean",
        "default": false
      }
    },
    "parameters_ui": {
      "num_gpus": {
        "ui:emptyValue": "",
        "ui:help": "Used to spread models over multiple GPUs. Leave empty to use default."
      }
    }
  }

=== transformerlab/transformerlab-api/transformerlab/plugins/openai_server/index.json
{
  "name": "OpenAI Server",
  "uniqueId": "openai_server",
  "description": "Connects to OpenAI's API to run hosted models like GPT-4 or GPT-3.5 via FastChat.",
  "plugin-format": "python",
  "type": "loader",
  "version": "0.1.1",
  "model_architectures": ["LlamaForCausalLM"],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {
    "model_name": {
    "title": "Model Name",
    "type": "string",
    "required": true,
    "default": "gpt-3.5-turbo"
  }
  },
  "supported_hardware_architectures": ["cpu"]
}

=== transformerlab/transformerlab-api/transformerlab/plugins/llama_cpp_server/index.json
{
  "name": "Llama-cpp Server",
  "uniqueId": "llama_cpp_server",
  "description": "Runs llama-cpp-python server that can run GGUF models that work well on CPU only machines.",
  "plugin-format": "python",
  "type": "loader",
  "version": "0.1.11",
  "model_architectures": ["GGUF"],
  "supported_hardware_architectures": ["cpu", "cuda", "mlx", "amd"],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {
    "n_gpu_layers": {
      "title": "Number of Models Layers to Offload to GPU (-1 for all, 'auto' for automatic selection)",
      "type": "string",
      "default": "auto"
    }
  }
}

=== transformerlab/transformerlab-api/transformerlab/plugins/openai_api_proxy_server/index.json
{
  "name": "OpenAI API Proxy Server",
  "uniqueId": "openai_api_proxy_server",
  "description": "A server that provides OpenAI-compatible RESTful APIs.",
  "plugin-format": "python",
  "type": "loader",
  "version": "1.0.11",
  "model_architectures": [
  ],
  "supported_hardware_architectures": ["cpu"],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {
    "max-model-len": {
      "title": "Maximum Model Length",
      "type": "integer"
    },
    "proxy_url": {
      "title": "Set Proxy URL",
      "type": "string",
      "default": "http://localhost:8000/v1/chat/completions"
    },
    "api_key": {
      "title": "Set API Key",
      "type": "string"
    }
  }
}

=== transformerlab/transformerlab-api/transformerlab/plugins/airllm_fastchat_server/index.json
{
  "name": "Fastchat Server",
  "uniqueId": "fastchat_server",
  "description": "Fastchat loads models for inference using Huggingface Transformers for generation.",
  "plugin-format": "python",
  "type": "loader",
  "version": "1.0.4",
  "model_architectures": [
    "CohereForCausalLM",
    "FalconForCausalLM",
    "GemmaForCausalLM",
    "Gemma2ForCausalLM",
    "GPTBigCodeForCausalLM",
    "LlamaForCausalLM",
    "MistralForCausalLM",
    "MixtralForCausalLM",
    "PhiForCausalLM",
    "Phi3ForCausalLM",
    "Qwen2ForCausalLM",
    "ExaoneForCausalLM",
    "T5ForConditionalGeneration"
  ],
  "supported_hardware_architectures": ["cpu", "cuda", "mlx"],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {
  "gpu_ids": {
          "title": "GPU IDs to use for Inference. Leaving blank will use all available GPUs",
          "type": "string",
          "default": ""
      },
    "eight_bit": {
      "title": "Enable 8-bit compression",
      "type": "boolean",
      "default": false
    }
  },
  "parameters_ui": {
    "gpu_ids": {
      "ui:help": "Specify a comma-separated list of GPU IDs to use for inference. The IDs for each GPU can be found in the Computer tab. For example: 0,1,2,3"
    }
  }
}

=== transformerlab/transformerlab-api/transformerlab/plugins/llamaindex_simple_document_search/index.json
{
  "name": "LlamaIndex Simple Document Search (RAG)",
  "uniqueId": "llamaindex_simple_document_search",
  "description": "",
  "plugin-format": "python",
  "type": "rag",
  "version": "0.0.12",
  "model_architectures": [],
  "supported_hardware_architectures": ["cpu", "cuda", "mlx", "amd"],
  "files": ["main.py", "setup.sh"],
  "setup-script": "setup.sh",
  "parameters": {
    "response_mode": {
      "title": "Response Mode",
      "default": "compact",
      "type": "string",
      "enum": [
        "compact",
        "refine",
        "tree_summarize",
        "simple_summarize",
        "no_text",
        "accumulate",
        "compact_accumulate"
      ]
    },
    "number_of_search_results": {
      "title": "Number of Retrieval Results",
      "type": "integer",
      "default": 2
    },
    "temperature": {
      "title": "Temperature",
      "type": "number",
      "default": 0.7,
      "minimum": 0.0,
      "maximum": 1.0,
      "multipleOf": 0.02
    },
    "context_window": {
      "title": "Maximum Input Length (in Tokens)",
      "type": "integer",
      "default": 4096
    },
    "num_output": {
      "title": "Size of Output (in Tokens)",
      "type": "integer",
      "default": 256
    },
    "chunk_size": {
      "title": "Chunk Size",
      "type": "integer",
      "default": 512
    },
    "chunk_overlap": {
      "title": "Chunk Overlap",
      "type": "integer",
      "default": 50
    },
    "use_reranker": {
      "title": "Use Reranker",
      "type": "boolean",
      "default": false
    },
    "reranker_model": {
      "title": "Reranker Model",
      "type": "string",
      "default": "cross-encoder/ms-marco-MiniLM-L-6-v2"
    },
    "reranker_top_n": {
      "title": "Reranker Top N",
      "type": "integer",
      "default": 20
    }
  },
  "parameters_ui": {
    "response_mode": {
      "ui:help": "LLama Index Response Mode. More info here https://tinyurl.com/3nurvee5"
    },
    "context_window": {
      "ui:help": "Number of tokens to include in the input context, which includes the combination of all the search results. Default is 4096."
    },
    "num_output": {
      "ui:help": "Number of tokens to include in the output. Input + Output Size should be less than model's Context Length. Default is 256."
    },
    "number_of_search_results": {
      "ui:help": "Number of search results to return. Too large and the context will become too big, too small and the LLM will not have enough candidate results to look at. Default is 2."
    },
    "temperature": {
      "ui:widget": "range",
      "ui:help": "Temperature for sampling in LLM. Lower values will result in more deterministic results, higher values will result in more random results. Default is 0.7."
    },
    "use_reranker": {
      "ui:help": "Use a reranker to re-rank the search results. Default is True."
    },
    "reranker_model": {
      "ui:help": "Reranker model to use. Default is cross-encoder/ms-marco-MiniLM-L-6-v2. Enter any reranker model from huggingface model hub"
    },
    "reranker_top_n": {
      "ui:help": "Top N search results to rerank. Default is 20."
    }
  }
}
